version: "3.8"

services:
  cookbook:
    image: cookbook
    container_name: cookbook
    volumes:
      - /tmp/cookbook:/cookbook_home
    environment:
      TZ: 'UTC'
    ports:
      - '8080:8080'
    depends_on:
      - mongodb
    restart: unless-stopped
  mongodb:
    image: mongo
    container_name: mongodb
    volumes:
      - /tmp/mongodb:/data/db
    ports:
      - '27017:27017'
    restart: unless-stopped
  jenkins:
      image: jenkins/jenkins
      container_name: jenkins
      user: root
      volumes:
        - /tmp/jenkins:/var/jenkins_home
      ports:
        - '8081:8080'
      restart: unless-stopped
  sonarqube:
    image: sonarqube
    container_name: sonarqube
    ports:
      - '9000:9000'
    restart: unless-stopped